default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: widget_db_pass
  host: 127.0.0.1
  maintenance_db: postgres

development:
  <<: *default
  database: widget_marketplace_development

test:
  <<: *default
  database: widget_marketplace_test

production:
  <<: *default
  database: widget_marketplace_production
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
